name: mind_game
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter


  ###### ================ UI ================= ######
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  flutter_modular: ^6.3.2
  flutter_screenutil: ^5.9.0

  cached_network_image: ^3.3.1
  toastification: ^2.3.0


  ###### ================ UTILS ================= ######
  localize_and_translate: ^6.0.7
  provider: ^6.1.2




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  hive_generator: ^2.0.1
  change_app_package_name: 

  # -------- App Icon Launcher ----------#
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo/app_logo.png"
  remove_alpha_ios: true

flutter_gen:
  output: lib/core/assets
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/

  
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo-Black.ttf
          weight: 900
